//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseFinalProject.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetreveAllPlayers", Namespace="http://schemas.datacontract.org/2004/07/TeamService")]
    [System.SerializableAttribute()]
    public partial class RetreveAllPlayers : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataSet dtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataSet dt {
            get {
                return this.dtField;
            }
            set {
                if ((object.ReferenceEquals(this.dtField, value) != true)) {
                    this.dtField = value;
                    this.RaisePropertyChanged("dt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetreveAllPlayerByPosition", Namespace="http://schemas.datacontract.org/2004/07/TeamService")]
    [System.SerializableAttribute()]
    public partial class RetreveAllPlayerByPosition : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataSet dtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataSet dt {
            get {
                return this.dtField;
            }
            set {
                if ((object.ReferenceEquals(this.dtField, value) != true)) {
                    this.dtField = value;
                    this.RaisePropertyChanged("dt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetreveAllPlayersByTeam", Namespace="http://schemas.datacontract.org/2004/07/TeamService")]
    [System.SerializableAttribute()]
    public partial class RetreveAllPlayersByTeam : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataSet dtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataSet dt {
            get {
                return this.dtField;
            }
            set {
                if ((object.ReferenceEquals(this.dtField, value) != true)) {
                    this.dtField = value;
                    this.RaisePropertyChanged("dt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetreveTeamWinLoss", Namespace="http://schemas.datacontract.org/2004/07/TeamService")]
    [System.SerializableAttribute()]
    public partial class RetreveTeamWinLoss : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataSet dtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataSet dt {
            get {
                return this.dtField;
            }
            set {
                if ((object.ReferenceEquals(this.dtField, value) != true)) {
                    this.dtField = value;
                    this.RaisePropertyChanged("dt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateTeamMember", Namespace="http://schemas.datacontract.org/2004/07/TeamService")]
    [System.SerializableAttribute()]
    public partial class UpdateTeamMember : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TeamIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Position {
            get {
                return this.PositionField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionField, value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeamId {
            get {
                return this.TeamIdField;
            }
            set {
                if ((this.TeamIdField.Equals(value) != true)) {
                    this.TeamIdField = value;
                    this.RaisePropertyChanged("TeamId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetreveTeamDetails", Namespace="http://schemas.datacontract.org/2004/07/TeamService")]
    [System.SerializableAttribute()]
    public partial class RetreveTeamDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataSet dtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataSet dt {
            get {
                return this.dtField;
            }
            set {
                if ((object.ReferenceEquals(this.dtField, value) != true)) {
                    this.dtField = value;
                    this.RaisePropertyChanged("dt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetreveSponsor", Namespace="http://schemas.datacontract.org/2004/07/TeamService")]
    [System.SerializableAttribute()]
    public partial class RetreveSponsor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataSet dtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataSet dt {
            get {
                return this.dtField;
            }
            set {
                if ((object.ReferenceEquals(this.dtField, value) != true)) {
                    this.dtField = value;
                    this.RaisePropertyChanged("dt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetreveAllTeams", Namespace="http://schemas.datacontract.org/2004/07/TeamService")]
    [System.SerializableAttribute()]
    public partial class RetreveAllTeams : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataSet dtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataSet dt {
            get {
                return this.dtField;
            }
            set {
                if ((object.ReferenceEquals(this.dtField, value) != true)) {
                    this.dtField = value;
                    this.RaisePropertyChanged("dt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/retreveAllPlayers", ReplyAction="http://tempuri.org/IService1/retreveAllPlayersResponse")]
        EnterpriseFinalProject.ServiceReference1.RetreveAllPlayers retreveAllPlayers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/retreveAllPlayers", ReplyAction="http://tempuri.org/IService1/retreveAllPlayersResponse")]
        System.Threading.Tasks.Task<EnterpriseFinalProject.ServiceReference1.RetreveAllPlayers> retreveAllPlayersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/retreveAllPlayerByPosition", ReplyAction="http://tempuri.org/IService1/retreveAllPlayerByPositionResponse")]
        EnterpriseFinalProject.ServiceReference1.RetreveAllPlayerByPosition retreveAllPlayerByPosition(string pos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/retreveAllPlayerByPosition", ReplyAction="http://tempuri.org/IService1/retreveAllPlayerByPositionResponse")]
        System.Threading.Tasks.Task<EnterpriseFinalProject.ServiceReference1.RetreveAllPlayerByPosition> retreveAllPlayerByPositionAsync(string pos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/retreveAllPlayersByTeam", ReplyAction="http://tempuri.org/IService1/retreveAllPlayersByTeamResponse")]
        EnterpriseFinalProject.ServiceReference1.RetreveAllPlayersByTeam retreveAllPlayersByTeam(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/retreveAllPlayersByTeam", ReplyAction="http://tempuri.org/IService1/retreveAllPlayersByTeamResponse")]
        System.Threading.Tasks.Task<EnterpriseFinalProject.ServiceReference1.RetreveAllPlayersByTeam> retreveAllPlayersByTeamAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/retreveTeamWinLoss", ReplyAction="http://tempuri.org/IService1/retreveTeamWinLossResponse")]
        EnterpriseFinalProject.ServiceReference1.RetreveTeamWinLoss retreveTeamWinLoss();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/retreveTeamWinLoss", ReplyAction="http://tempuri.org/IService1/retreveTeamWinLossResponse")]
        System.Threading.Tasks.Task<EnterpriseFinalProject.ServiceReference1.RetreveTeamWinLoss> retreveTeamWinLossAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateTeamMembber", ReplyAction="http://tempuri.org/IService1/UpdateTeamMembberResponse")]
        string UpdateTeamMembber(EnterpriseFinalProject.ServiceReference1.UpdateTeamMember utm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateTeamMembber", ReplyAction="http://tempuri.org/IService1/UpdateTeamMembberResponse")]
        System.Threading.Tasks.Task<string> UpdateTeamMembberAsync(EnterpriseFinalProject.ServiceReference1.UpdateTeamMember utm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/retreveTeamDetails", ReplyAction="http://tempuri.org/IService1/retreveTeamDetailsResponse")]
        EnterpriseFinalProject.ServiceReference1.RetreveTeamDetails retreveTeamDetails(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/retreveTeamDetails", ReplyAction="http://tempuri.org/IService1/retreveTeamDetailsResponse")]
        System.Threading.Tasks.Task<EnterpriseFinalProject.ServiceReference1.RetreveTeamDetails> retreveTeamDetailsAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/retreveSponsor", ReplyAction="http://tempuri.org/IService1/retreveSponsorResponse")]
        EnterpriseFinalProject.ServiceReference1.RetreveSponsor retreveSponsor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/retreveSponsor", ReplyAction="http://tempuri.org/IService1/retreveSponsorResponse")]
        System.Threading.Tasks.Task<EnterpriseFinalProject.ServiceReference1.RetreveSponsor> retreveSponsorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/retreveAllTeams", ReplyAction="http://tempuri.org/IService1/retreveAllTeamsResponse")]
        EnterpriseFinalProject.ServiceReference1.RetreveAllTeams retreveAllTeams();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/retreveAllTeams", ReplyAction="http://tempuri.org/IService1/retreveAllTeamsResponse")]
        System.Threading.Tasks.Task<EnterpriseFinalProject.ServiceReference1.RetreveAllTeams> retreveAllTeamsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : EnterpriseFinalProject.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<EnterpriseFinalProject.ServiceReference1.IService1>, EnterpriseFinalProject.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EnterpriseFinalProject.ServiceReference1.RetreveAllPlayers retreveAllPlayers() {
            return base.Channel.retreveAllPlayers();
        }
        
        public System.Threading.Tasks.Task<EnterpriseFinalProject.ServiceReference1.RetreveAllPlayers> retreveAllPlayersAsync() {
            return base.Channel.retreveAllPlayersAsync();
        }
        
        public EnterpriseFinalProject.ServiceReference1.RetreveAllPlayerByPosition retreveAllPlayerByPosition(string pos) {
            return base.Channel.retreveAllPlayerByPosition(pos);
        }
        
        public System.Threading.Tasks.Task<EnterpriseFinalProject.ServiceReference1.RetreveAllPlayerByPosition> retreveAllPlayerByPositionAsync(string pos) {
            return base.Channel.retreveAllPlayerByPositionAsync(pos);
        }
        
        public EnterpriseFinalProject.ServiceReference1.RetreveAllPlayersByTeam retreveAllPlayersByTeam(int id) {
            return base.Channel.retreveAllPlayersByTeam(id);
        }
        
        public System.Threading.Tasks.Task<EnterpriseFinalProject.ServiceReference1.RetreveAllPlayersByTeam> retreveAllPlayersByTeamAsync(int id) {
            return base.Channel.retreveAllPlayersByTeamAsync(id);
        }
        
        public EnterpriseFinalProject.ServiceReference1.RetreveTeamWinLoss retreveTeamWinLoss() {
            return base.Channel.retreveTeamWinLoss();
        }
        
        public System.Threading.Tasks.Task<EnterpriseFinalProject.ServiceReference1.RetreveTeamWinLoss> retreveTeamWinLossAsync() {
            return base.Channel.retreveTeamWinLossAsync();
        }
        
        public string UpdateTeamMembber(EnterpriseFinalProject.ServiceReference1.UpdateTeamMember utm) {
            return base.Channel.UpdateTeamMembber(utm);
        }
        
        public System.Threading.Tasks.Task<string> UpdateTeamMembberAsync(EnterpriseFinalProject.ServiceReference1.UpdateTeamMember utm) {
            return base.Channel.UpdateTeamMembberAsync(utm);
        }
        
        public EnterpriseFinalProject.ServiceReference1.RetreveTeamDetails retreveTeamDetails(int id) {
            return base.Channel.retreveTeamDetails(id);
        }
        
        public System.Threading.Tasks.Task<EnterpriseFinalProject.ServiceReference1.RetreveTeamDetails> retreveTeamDetailsAsync(int id) {
            return base.Channel.retreveTeamDetailsAsync(id);
        }
        
        public EnterpriseFinalProject.ServiceReference1.RetreveSponsor retreveSponsor() {
            return base.Channel.retreveSponsor();
        }
        
        public System.Threading.Tasks.Task<EnterpriseFinalProject.ServiceReference1.RetreveSponsor> retreveSponsorAsync() {
            return base.Channel.retreveSponsorAsync();
        }
        
        public EnterpriseFinalProject.ServiceReference1.RetreveAllTeams retreveAllTeams() {
            return base.Channel.retreveAllTeams();
        }
        
        public System.Threading.Tasks.Task<EnterpriseFinalProject.ServiceReference1.RetreveAllTeams> retreveAllTeamsAsync() {
            return base.Channel.retreveAllTeamsAsync();
        }
    }
}
